name: Test output formats

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions: {}

jobs:
  test-sarif-presentation:
    name: Test SARIF presentation
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-sarif-presentation')
    permissions:
      pull-requests: write # for 'Leave comment' step
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Run zizmor
        run: |
          cargo run -- --format sarif . > results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        with:
          sarif_file: results.sarif
          category: zizmor-test-sarif-presentation

      - name: Leave comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          URL: "https://github.com/zizmorcore/zizmor/security/code-scanning?query=pr%3A${{ github.event.pull_request.number }}+is%3Aopen+sort%3Acreated-desc"
        run: |
          gh pr comment "${PR_NUMBER}" \
            --body ":robot: SARIF results: ${URL}"

  test-github-presentation:
    name: Test GitHub annotations presentation
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-github-presentation')
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Run zizmor
        run: |
          # Normally we'd want a workflow to fail if the audit fails,
          # but we're only testing presentation here.
          cargo run \
            -- \
            --no-exit-codes \
            --format github \
            crates/zizmor/tests/integration/test-data/several-vulnerabilities.yml

  test-plain-presentation:
    name: Test plain text presentation
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-plain-presentation')
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Run zizmor
        run: |
          # Normally we'd want a workflow to fail if the audit fails,
          # but we're only testing presentation here.
          cargo run \
            -- \
            --no-exit-codes \
            --format plain \
            crates/zizmor/tests/integration/test-data/several-vulnerabilities.yml
